name: Unzip to Root

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5   # use v5 if available, else v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip safely
        run: unzip -o auth-system-github.zip -x "*.git*" -d .

      - name: List files
        run: ls -la
