name: Unzip Folder

on:
  workflow_dispatch:   # run manually from Actions tab
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Remove git lock (safety)
        run: rm -f .git/index.lock || true

      - name: Unzip file to root
        run: unzip -o pulse.zip -x "*.git*" -d .

      - name: Show extracted files
        run: ls -la

      - name: Commit extracted files (optional)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "pulse.zip" || echo "No changes"
          git push
